### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by ss892714028** [zilliztech/MolSearch#14]
This repo has not been updated for over half a year, however, currently, there are still users being directed to this repository.

Is there any future plans for this project? Is it going to be compatible with Milvus 2.x? What are the differences between this project and the molsearch project under [Milvus bootcamp repo](https://github.com/milvus-io/bootcamp/tree/master/solutions/molecular_similarity_search)?

**Comment by shiyu22** [comment]
Thanks for the heads up. 

This repo will no longer be maintained, please visit https://github.com/milvus-io/bootcamp/tree/master/solutions/molecular_similarity_search. And I will add it to the RADME.md.
